// =============================================================================
// PAGE RENDER SERVER COMPONENT - Catch-all route for published pages
// Renders user-facing pages generated by Puck
// Follows puck-main next-ai recipe pattern with ISR
// =============================================================================

import {Client} from "./client";
import {notFound} from "next/navigation";
import {Metadata} from "next";
import {getPage} from "@/lib/get-page";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ puckPath: string[] }>;
}): Promise<Metadata> {
  const { puckPath = [] } = await params;
  const path = `/${puckPath.join("/")}`;
  const data = await getPage(path);

  return {
    title: data?.root?.props?.title || path,
  };
}

export default async function Page({
  params,
}: {
  params: Promise<{ puckPath: string[] }>;
}) {
  const { puckPath = [] } = await params;
  const path = `/${puckPath.join("/")}`;
  const data = await getPage(path);

  if (!data) {
    return notFound();
  }

  return <Client data={data} />;
}

// Force static generation with ISR
// Pages will be cached and revalidated on publish
export const dynamic = "force-static";

// Revalidate every 60 seconds (optional - can be removed for true static)
// export const revalidate = 60;
