// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { tracing, metrics, logger } from '@/lib/otel-observability';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const baseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce', // Use PKCE for more secure OAuth flow
  }
});

/**
 * Wrapper around Supabase client with distributed tracing and metrics
 */
export const supabase = new Proxy(baseClient, {
  get(target, prop) {
    const value = Reflect.get(target, prop);

    // Intercept database operations for tracing
    if (typeof value === 'function' && ['select', 'insert', 'update', 'delete', 'rpc'].includes(prop as string)) {
      return function <T = unknown>(...args: unknown[]) {
        const operationName = `supabase_${String(prop)}`;
        const spanContext = tracing.startTrace(operationName);

        const startTime = Date.now();

        try {
          logger.debug(`Supabase ${String(prop)} operation`, { args });
          const result = value.apply(target, args);

          // Handle both sync and async results
          if (result && typeof result.then === 'function') {
            return result
              .then((res: T) => {
                const duration = Date.now() - startTime;
                metrics.recordLatency(`supabase_${String(prop)}_duration_ms`, duration);
                tracing.endSpan(spanContext.spanId, 'ok');

                // Log slow queries
                if (duration > 500) {
                  logger.warn(`Slow Supabase query: ${String(prop)}`, { duration, args });
                }

                return res;
              })
              .catch((error: Error) => {
                const duration = Date.now() - startTime;
                logger.error(`Supabase ${String(prop)} error`, { error, duration });
                metrics.incrementCounter(`supabase_${String(prop)}_errors`);
                tracing.endSpan(spanContext.spanId, 'error', error);
                throw error;
              });
          }

          const duration = Date.now() - startTime;
          metrics.recordLatency(`supabase_${String(prop)}_duration_ms`, duration);
          tracing.endSpan(spanContext.spanId, 'ok');

          return result;
        } catch (error) {
          const duration = Date.now() - startTime;
          logger.error(`Supabase ${String(prop)} error`, { error, duration });
          metrics.incrementCounter(`supabase_${String(prop)}_errors`);
          tracing.endSpan(spanContext.spanId, 'error', error as Error);
          throw error;
        }
      };
    }

    // Intercept auth operations
    if (typeof value === 'function' && ['signIn', 'signUp', 'signOut', 'getSession'].includes(prop as string)) {
      return function <T = unknown>(...args: unknown[]) {
        const operationName = `supabase_auth_${String(prop)}`;
        const spanContext = tracing.startCriticalTrace(operationName); // Auth is critical

        const startTime = Date.now();

        try {
          logger.debug(`Supabase auth ${String(prop)}`, { args });
          const result = value.apply(target, args);

          if (result && typeof result.then === 'function') {
            return result
              .then((res: T) => {
                const duration = Date.now() - startTime;
                metrics.recordLatency(`supabase_auth_${String(prop)}_duration_ms`, duration);
                tracing.endSpan(spanContext.spanId, 'ok');
                return res;
              })
              .catch((error: Error) => {
                const duration = Date.now() - startTime;
                logger.error(`Supabase auth ${String(prop)} error`, { error, duration });
                metrics.incrementCounter(`supabase_auth_errors`);
                tracing.endSpan(spanContext.spanId, 'error', error);
                throw error;
              });
          }

          return result;
        } catch (error) {
          const duration = Date.now() - startTime;
          logger.error(`Supabase auth ${String(prop)} error`, { error, duration });
          metrics.incrementCounter(`supabase_auth_errors`);
          tracing.endSpan(spanContext.spanId, 'error', error as Error);
          throw error;
        }
      };
    }

    return value;
  },
});
